# Create apps namespace
k8s_yaml("00-namespace.yml")

# ACH
docker_build('moov/ach:latest', './ach')
k8s_resource('ach', './ach/10-ach.yml', port_forwards='8080:8080')

# Auth
docker_build('moov/auth:latest', './auth')
k8s_resource('auth', './auth/11-auth.yml', port_forwards='8081:8080')

# OFAC
docker_build('moov/ofac:latest', './ofac')
k8s_resource('ofac', './ofac/13-ofac.yml', port_forwards='8084:8080')

# Paygate
docker_build('moov/paygate:latest', './paygate')
k8s_resource('paygate', './paygate/12-paygate.yml', port_forwards='8082:8080')
