# Create apps namespace
k8s_yaml("00-namespace.yml")

k8s_resource('proxy', './proxy/proxy.yml', port_forwards='9000:9000')
k8s_resource('ach', './ach/10-ach.yml')
k8s_resource('auth', './auth/11-auth.yml')
k8s_resource('paygate', './paygate/12-paygate.yml')
k8s_resource('ofac', './ofac/13-ofac.yml')
# k8s_resource('fed', './fed/15-fed.yml') # TODO(adam): need to download files on startup
